INSERT INTO companies (name, zip_code, website) VALUES ('TOLA SALES GROUP', '78229', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('FOUNDATION CORRECTIONS INC', '94002', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('DWIGHT HARRISON VW', '30078', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('DIRECTV', '38006', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('SAINT PAUL RADIOLOGY', '55109', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('PIZZA HUT', '44667', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('LINDA GROUP USA LLC', '33178', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('DIAMOND BLUE POOL SERVICE', '33316', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('PREMIERE MORTGAGE CAPITAL', '28031', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('BOSTON STUDIO INC', '02119', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('A G M DESIGNS', '77521', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('NXP SEMICONDUCTOR INC', '48377', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('JEFFREY ROBERTS H', '35640', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('RINCON MUSICAL', '07087', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('AAA MOVING & STORAGE', '28037', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('SWIFT CONSTRUCTION', '45056', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('EPICBOARDSHOP', '84101', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('BEAR ZOO LLC', '78258', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('US POST OFFICE', '57761', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('MIDNIGHT FRIENDS LLC', '19422', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('FIG TREE MANOR BED BREAKFAST', '75801', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('PONDEROSA SEPTIC & GREASE', '78363', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('TIM DIEBALL', '53115', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('MEMDEES RESTAURANT', '19143', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('EPICBOARDSHOP BRANCH', '', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('SNELLING & SNELLING', '65804', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('BISON SECURITY CO INC', '14609', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('HENRIETTA TRANSPORT', '60606', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('FISCHER GROUP THE FISCHER HMS', '45140', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('JCF INTERNATIONAL AIRCRAFT', '60046', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('LEWISGALE INTERNAL MEDICINE', '24073', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('BRYANT FAMILY & COSMETIC DENTISTRY', '29651', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('JAMES AND KELSEN', '95338', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('ODELLA''S ANTIQUES & NOSTALGIA', '95338', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('ALL UNDER ONE ROOF', '1841', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('TIM DIEBALL', '53113', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('VANDYKE JACQUELINE L', '45701', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('WALDININ TUBURSKY INC', '45701', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('FOUNTAIN HILLS MEDICAL CLINIC', '85268', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('JEFFREY S BENSON PAINTING', '34120', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('CAMPUS DRY CLEANING', '44074', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('JOHN ALDEN LIFE INSURANCE CO', '77042', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('R & G FISH LLC', '77979', NULL);
INSERT INTO companies (name, zip_code, website) VALUES ('REDBOX', '17602', NULL);